### ISSUE TITLE
object collection "schema" proposal

### ISSUE THREAD

**Issue by cynexit** [HolmesProcessing/Holmes-Storage#1]
Proposed schema:

```json
{
   "md5":"098f6bcd4621d373cade4e832627b4f6",
   "sha1":"a94a8fe5ccb19ba61c4c0873d391e987982fbbd3",
   "sha256":"9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
   "submission":[
      {
         "user_id":1,
         "source":"x",
         "name":"test.exe",
         "date":"2015-11-24T15:23:29Z"
      },
      {
         "user_id":4,
         "source":"y",
         "name":"test23.exe",
         "date":"2015-11-24T19:23:29Z"
      }
   ]
}
```

Where we should use sha256 as the shard key.

**Comment by cynexit** [comment]
Update: Split it into two collections:

**objects**
```json
{
   "md5":"098f6bcd4621d373cade4e832627b4f6",
   "sha1":"a94a8fe5ccb19ba61c4c0873d391e987982fbbd3",
   "sha256":"9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08"
}
```

**submissions**
```json
{
    "sha256":"9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
    "user_id":1,
    "source":"x",
    "name":"test.exe",
    "date":"2015-11-24T15:23:29Z"
}
```

and have multiple submissions for each object.

**Comment by webstergd** [comment]
Do we want to add addition meta information such as the following? 

object_reference - capture if it was a primary or secondary (dropped or carved) submission
object_category - category the object would fall under
object_type - MIME type [1]

[1] http://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by webstergd** [comment]
New proposal for object as follows:
{
    "_id": UUID,
    "sha1: str,
    "sha256": str,
    "md5": str,
    "mime": str,
    "source": []str,
    "obj_name": []str,
}

New proposal for submission as follows:
{
    "_id": UUID
    "object": UUID,
    "user_id": str,
    "source": str,
    "date": ISO8601,
    "obj_name": str,
    "tags": []str,
    "comment": str,
}

**Comment by webstergd** [comment]
Cassandra does have the InetAddressType which should probably be used. we could then use a string for domain and email. However, we still need some more logic on Domain as we will probably want to capture TLD and subdomains.

**Comment by webstergd** [comment]
Final Scheme is as follows

**Objects**
```json
{
"_id": UUID,
"sha1: str,
"sha256": str,
"md5": str,
"mime": str,
"source": []str,
"obj_name": []str,
"submissions" []UUID,
}
```

**submission**
```json
{
"_id": UUID
"object": UUID,
"user_id": str,
"source": str,
"date": ISO8601,
"obj_name": str,
"tags": []str,
"comment": str,
}
```
