### ISSUE TITLE
results collection "schema" proposal

### ISSUE THREAD

**Issue by cynexit** [HolmesProcessing/Holmes-Storage#2]
Proposed schema:

```json
{
   "_id": ObjectID("..."),
   "schema_version":"0.1",
   "user_id":"0.1",
   "source":{
      "info":"",
      "contact":""
   },
   "service":{
      "name":"yara",
      "version":"1.0",
      "config":{

      }
   },
   "object_type":"sample",
   "results":{

   },
   "date":"2015-11-24T15:23:29Z",
   "watchguard":{
      "log":[
         "msg1",
         "msg2"
      ],
      "status":"done"
   }
}
```

**Comment by webstergd** [comment]
Based on our conversation we will be flattening the structure. This will make it easier to leverage other DB architectures like cassandra, elastic search, etc. 

Question/comment:
1) I propose source_ID and user_id should be a hash that references a separate db object that will contains more information. This way it is easier to adjust contact information, source names, etc. 
2) object_type - do we want that to be a generic name such as sample? or do we want that to be a MIME type? Do we really want both object_category and object_type?

New proposal is as follows:
{
   "_id": ObjectID("..."),
   "schema_version": <string "1.0">,
   "user_id": <string hash>,
   "source_id": <string hash>,
   "service_name": <string "name">,
   "service_version": <string "1.0">,
   "service_config": <json string> ,
   "object_category": <string "category">,
   "object_type": <string "MIME Type [1]">,
   "results": <json string>,
   "date": " <ISO 8601 ... 2015-11-24T15:23:29Z>,
   "watchguard_status": <string [complete, incomplete, or error]>
   "watchguard_log": [ <string "msg1>, <string msg2>, ... ]
   "watchguard_version": <string "1.0">
}

[1] http://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by webstergd** [comment]
Would be nice to also include a tag field. This field can be a list of strings that will help with information identification and retrieval. For example, tag: ["debug_test"]

**Comment by webstergd** [comment]
switch ID to UUID:

New proposal is as follows:
{
"_id": UUID4,
"schema_version": ,
"user_id": ,
"source_id": ,
"service_name": ,
"service_version": ,
"service_config": ,
"object_category": ,
"object_type": ,
"results": ,
"date": " ,
"watchguard_status": 
"watchguard_log": [ , , ... ]
"watchguard_version": 
}

**Comment by webstergd** [comment]
switch ID to UUID:

New proposal is as follows:
{
"_id": UUID4,
"schema_version": str,
"user_id": str,
"source_id": []str,
"source_tag: []str,
"service_name": str,
"service_version": str,
"service_config": json,
"object_category": []str,
"object_type": str,
"results": json,
"started_date_time": " ISO8601,
"finished_date_time": " ISO8601,
"watchguard_status": str
"watchguard_log": json
"watchguard_version": str
}

**Comment by webstergd** [comment]
Should we add a comment to results? this way an analysts can add an analytic comment

**Comment by zhanif3** [comment]
Like that, but do we want to replicate across the analytical result fields, or only on the root sample? Ultimately that's a UI/UX concern that is reflected in the backend, I would think.

**Comment by webstergd** [comment]
Right now only submissions have comments. This makes sense as I can place a source, tag (kinda subsource), and comment for why an analysts submitted a file. Results has source and tags only. 

Adding an option to store a completely separate comment would allow a comment on why a task was submitted to a sample...additionally it could allow the analysts to flag the results with a comment (if we decide to allow this later...I know, post modifying anything can be an issue)

**Comment by webstergd** [comment]
Final Scheme
```json
{
"_id": UUID,
"sha256": str,
"schema_version": str,
"user_id": str,
"source_id": []str,
"source_tag: []str,
"service_name": str,
"service_version": str,
"service_config": json,
"object_category": []str,
"object_type": str,
"results": json,
"tags": []str,
"started_date_time": " ISO8601,
"finished_date_time": " ISO8601,
"watchguard_status": str,
"watchguard_log": []str,
"watchguard_version": str,
"comment": str
}
```
