### ISSUE TITLE
UUIDs

### ISSUE THREAD

**Issue by cynexit** [HolmesProcessing/Holmes-Storage#6]
We should generate the UUIDs needed for `results`, `submissions` etc. inside the storer and don't offload this to the database. Reason being is that this way we don't need to use wrappers for "auto increment ids", "bson uuids" and so on. Would result in cleaner code.

**Comment by cynexit** [comment]
After a long time testing and carefully evaluation pros and cons we decided not to do this. The main reason is that there arise many new problems from this for distributed setups which would need a service like twitters snowflake to be solved.
We decided against this additional application overhead for now and the foreseeable future.

**Comment by webstergd** [comment]
concur

**Comment by ms-xy** [comment]
`func (s StorerCassandra) StoreSubmission(submission *storerGeneric.Submission) error {
	id, err := gocql.RandomUUID()
`

`func RandomUUID() (UUID, error) {
	var u UUID
	_, err := io.ReadFull(rand.Reader, u[:])
	if err != nil {
		return u, err
	}
	u[6] &= 0x0F // clear version
	u[6] |= 0x40 // set version to 4 (random uuid)
	u[8] &= 0x3F // clear variant
	u[8] |= 0x80 // set to IETF variant
	return u, nil
}`

https://github.com/gocql/gocql/blob/master/uuid.go
Line 100

just dropping this in here ;)
